Repository Woosmap/expo_plugin_geofencing_batch, pull requests merged in 2024-11, with the labels that each got.

#2 Android implementation
  android/build.gradle
  android/src/main/AndroidManifest.xml
  android/src/main/java/expo/modules/geofencingbatchplugin/GeofencingEventsReceiver.kt
  android/src/main/java/expo/modules/geofencingbatchplugin/WoosmapExpoLifecycleListener.kt
  android/src/main/java/expo/modules/geofencingbatchplugin/WoosmapExpoPackage.kt
  android/src/main/java/expo/modules/geofencingbatchplugin/WoosmapExpoPluginGeofencingBatchModule.kt
  example/App.tsx
  example/app.json
  example/package.json
  example/react-native.config.js
  example/withBatchApiKey.js
  expo-module.config.json
  src/configWoosmapGeofencingAndroid.ts
  src/index.ts
Labels: enhancement

#4 Dev/cicd
  .github/workflows/OnNPM.yaml
  .github/workflows/predict_version.yml
  CHANGELOG.md
  whatsnew.md
Labels: Patch :bug:

#5 Renamed iOS plugin module
  .github/workflows/OnNPM.yaml
  .github/workflows/predict_version.yml
  .npmignore
  expo-module.config.json
  ios/GeofencingEventsReceiver.swift
  package.json
  whatsnew.md
Labels: Minor :sparkles:

#6 Fix batch attribute errors
  android/src/main/java/expo/modules/geofencingbatchplugin/GeofencingEventsReceiver.kt
  expo-module.config.json
  ios/GeofencingEventsReceiver.swift
  ios/WoosmapExpoPluginGeofencingBatchModule.swift
  package.json
  whatsnew.md
Labels: Patch :bug:

#7 Parse int data to batch event
  ios/GeofencingEventsReceiver.swift
  package.json
  whatsnew.md
Labels: Patch :bug:

#10 User properties
  CHANGELOG.md
  ios/GeofencingEventsReceiver.swift
  package.json
  whatsnew.md
Labels: enhancement, Major :star2:

#11 Remove Empty property
  ios/GeofencingEventsReceiver.swift
  package.json
  whatsnew.md
Labels: enhancement, Patch :bug:
